spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/data_business
        username: postgres
        password: password
        hikari:
            driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        database: postgresql
        show-sql: true
